from core.diagnostics import best_manager_move
from core.formatters import direction, money, pct


def build_rules_manager_brief(metrics, diagnosis, priorities, health, period_change) -> str:
    priority_lines = "\n".join(f"- {priority}" for priority in priorities)
    return f"""Operational Health: {health}

The team generated {money(metrics['total_revenue'])} from {metrics['total_sales']:,.0f} sales on {metrics['total_leads']:,.0f} leads issued.

Primary bottleneck: {diagnosis['primary_bottleneck']}
Likely cause: {diagnosis['likely_cause']}
Recommended manager action: {diagnosis['manager_action']}
Coaching move: {diagnosis['coaching_move']}
Suggested roleplay: {diagnosis['roleplay']}

Top revenue producer: {diagnosis['best_rep']['Rep']} at {money(diagnosis['best_rep']['Revenue'])}
Rep to review: {diagnosis['review_rep']['Rep']} based on lowest NSLI
Strongest lead source: {diagnosis['best_source']['Lead Source']} at {money(diagnosis['best_source']['NSLI'])} NSLI
Lead source to review: {diagnosis['review_source']['Lead Source']} at {money(diagnosis['review_source']['NSLI'])} NSLI

What changed: {period_change['label']}
Revenue: {direction(period_change['revenue_change'], is_money=True)}
Demo Rate: {direction(period_change['demo_change'], is_pct=True)}
Close Rate: {direction(period_change['close_change'], is_pct=True)}
NSLI: {direction(period_change['nsli_change'], is_money=True)}

Top manager priorities:
{priority_lines}
"""


def build_manager_report(metrics, targets, diagnosis, priorities, health, period_change, enhanced_brief) -> str:
    priority_lines = "\n".join(f"{index + 1}. {priority}" for index, priority in enumerate(priorities))
    return f"""# OpsPilot AI Manager Report

## AI-Enhanced Manager Brief
{enhanced_brief}

## Executive Summary Scorecard
Operational Health: {health}
Primary Bottleneck: {diagnosis['primary_bottleneck']}
Best Manager Move This Week: {best_manager_move(diagnosis)}
Strongest Opportunity: Protect {diagnosis['best_source']['Lead Source']} and study why it is producing stronger NSLI.

## KPI Snapshot
Revenue: {money(metrics['total_revenue'])}
Leads Issued: {metrics['total_leads']:,.0f}
Demos: {metrics['total_demos']:,.0f}
Sales: {metrics['total_sales']:,.0f}
Demo Rate: {pct(metrics['demo_rate'])}
Close Rate: {pct(metrics['close_rate'])}
Average Sale: {money(metrics['avg_sale'])}
NSLI: {money(metrics['nsli'])}

## What Changed
{period_change['label']}
Revenue: {direction(period_change['revenue_change'], is_money=True)}
Demo Rate: {direction(period_change['demo_change'], is_pct=True)}
Close Rate: {direction(period_change['close_change'], is_pct=True)}
NSLI: {direction(period_change['nsli_change'], is_money=True)}

## Top 3 Manager Priorities
{priority_lines}

## Manager Diagnosis
Likely Cause: {diagnosis['likely_cause']}
Recommended Action: {diagnosis['manager_action']}
Coaching Move: {diagnosis['coaching_move']}
Suggested Roleplay: {diagnosis['roleplay']}

---
Generated by OpsPilot AI.
"""
